from .ArticleController import ArticleController
from .UserController import UserController
from .OtpController import OtpController
from .TransliterationController import TransliterationController
from .PegonScriptController import PegonScriptController
